language: r
sudo: false
cache: packages
r_packages:
  - covr

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" _R_CHECK_TESTS_NLINES_=0

repos:
  XRAN: https://xran.yihui.org

before_install:
  - "curl -L https://xran.yihui.org/.gitconfig -o ~/.gitconfig"

after_success:
  - Rscript -e 'covr::codecov()'
  - "(curl -L https://xran.yihui.org/r-xran | bash)"
